apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy # This is base64 encoding, to get this echo -n mongouser | base64 in terminal where mongouser is the word we want to encode in base64
  mongo-password: bW9uZ29wYXNzd29yZA==